### ISSUE TITLE
should this be "self" instead of "slef"?

### ISSUE THREAD

**Issue by DougAnderson444** [mir-omid/DAC-from-EQS#2]
should this be "self" instead of "slef"?

https://github.com/mir-omid/DAC-from-EQS/blob/a4ccce3c50ac4c9d68f2439e244b53284ba6ee6d/core/zkp.py#L12-L17

It occurs a number of times in this file like this.

**Comment by mir-omid** [comment]
Yes true, i fixed it, thanks
